import * as fs from 'node:fs';
import * as path from 'node:path';
import { MemoRecord, ProjectMetadata } from './types.js';
import { getProjectMetadata, getVaultRoot } from './vault.js';
import { parseRecord } from './schema.js';
import { applyTrapClassification, occurrenceOf } from './recurrence.js';

const SEVERITY_WEIGHT: Record<string, number> = {
  critical: 4,
  high: 3,
  medium: 2,
  low: 1
};

/**
 * Scan all records inside a project vault directory.
 */
export function scanProjectRecords(
  projectVaultPath: string
): MemoRecord[] {
  const records: MemoRecord[] = [];
  if (!fs.existsSync(projectVaultPath)) {
    return records;
  }

  const subdirs = fs.readdirSync(projectVaultPath, { withFileTypes: true });
  for (const dir of subdirs) {
    if (dir.isDirectory()) {
      const dirPath = path.join(projectVaultPath, dir.name);
      const files = fs.readdirSync(dirPath);
      for (const file of files) {
        if (file.endsWith('.md')) {
          const filePath = path.join(dirPath, file);
          try {
            const content = fs.readFileSync(filePath, 'utf8');
            const parsed = parseRecord(content, filePath);
            records.push(parsed);
          } catch {
            // Ignore unparseable files or scratch non-records
          }
        }
      }
    }
  }

  return records;
}

/**
 * Compile TRAPS.md view from trap records.
 */
export function generateTrapsView(metadata: ProjectMetadata | null, traps: MemoRecord[]): string {
  const title = metadata?.displayName || metadata?.projectId || 'Project';
  const now = new Date().toISOString();

  const activeTraps = traps
    .filter((t) => t.frontmatter.status === 'active')
    .sort((a, b) => {
      const weightA = SEVERITY_WEIGHT[a.frontmatter.severity || 'medium'] || 0;
      const weightB = SEVERITY_WEIGHT[b.frontmatter.severity || 'medium'] || 0;
      if (weightB !== weightA) return weightB - weightA;
      return (b.frontmatter.updated || '').localeCompare(a.frontmatter.updated || '');
    });

  const inactiveTraps = traps
    .filter((t) => t.frontmatter.status !== 'active')
    .sort((a, b) => (b.frontmatter.updated || '').localeCompare(a.frontmatter.updated || ''));

  let md = `# Anti-Regression Traps — ${title}

<!-- AUTO-GENERATED BY spec-memo — DO NOT EDIT DIRECTLY -->
*Last compiled: ${now}*
*Total active traps: ${activeTraps.length}*

`;

  if (activeTraps.length === 0) {
    md += `*No active traps recorded for this project yet.*\n\n`;
  } else {
    md += `## Active Traps\n\n`;
    for (const trap of activeTraps) {
      const sev = (trap.frontmatter.severity || 'medium').toUpperCase();
      const name = trap.frontmatter.title || trap.frontmatter.id;
      const patterns = (trap.frontmatter.pathPatterns || []).join(', ') || 'all';
      const relPath = `./traps/${trap.frontmatter.id}.md`;

      md += `### [${sev}] ${name} ([${trap.frontmatter.id}](${relPath}))\n\n`;
      md += `- **Path Patterns:** \`${patterns}\` | **Wikilink:** \`[[${trap.frontmatter.id}]]\`\n`;
      const classified = applyTrapClassification(trap.frontmatter, trap.body);
      const layer = classified.layer || 'other';
      const occurrences = occurrenceOf(trap.frontmatter);
      md += `- **Severity:** \`${trap.frontmatter.severity || 'medium'}\` | **Layer:** \`${layer}\` | **Occurrences:** \`${occurrences}\` | **Source:** \`${trap.frontmatter.source}\` | **Updated:** \`${trap.frontmatter.updated}\`\n`;
      if (trap.frontmatter.supersedes) {
        md += `- **Supersedes:** \`[[${trap.frontmatter.supersedes}]]\`\n`;
      }
      md += `\n${trap.body}\n\n---\n\n`;
    }
  }

  if (inactiveTraps.length > 0) {
    md += `## Archived & Superseded Traps\n\n`;
    for (const trap of inactiveTraps) {
      const name = trap.frontmatter.title || trap.frontmatter.id;
      const relPath = `./traps/${trap.frontmatter.id}.md`;
      md += `- **[${trap.frontmatter.status.toUpperCase()}]** [\`${trap.frontmatter.id}\`](${relPath}) (\`[[${trap.frontmatter.id}]]\`): ${name} (updated: ${trap.frontmatter.updated})\n`;
    }
    md += `\n`;
  }

  return md;
}

/**
 * Compile DECISIONS.md view from decision records.
 */
export function generateDecisionsView(metadata: ProjectMetadata | null, decisions: MemoRecord[]): string {
  const title = metadata?.displayName || metadata?.projectId || 'Project';
  const now = new Date().toISOString();

  const sorted = [...decisions].sort((a, b) =>
    (b.frontmatter.updated || '').localeCompare(a.frontmatter.updated || '')
  );

  const accepted = sorted.filter((d) => d.frontmatter.status === 'active' || d.frontmatter.status === 'shipped');
  const proposed = sorted.filter((d) => d.frontmatter.status === 'paused');
  const superseded = sorted.filter((d) => d.frontmatter.status === 'superseded' || d.frontmatter.status === 'archived');

  let md = `# Architecture Decision Records — ${title}

<!-- AUTO-GENERATED BY spec-memo — DO NOT EDIT DIRECTLY -->
*Last compiled: ${now}*
*Total decisions: ${decisions.length} (Accepted: ${accepted.length}, Proposed: ${proposed.length}, Superseded: ${superseded.length})*

## Summary

| ID | Title | Status | Updated | Supersedes |
|---|---|---|---|---|
`;

  if (decisions.length === 0) {
    md += `| - | *No decisions recorded* | - | - | - |\n\n`;
  } else {
    for (const d of sorted) {
      const dTitle = d.frontmatter.title || d.frontmatter.id;
      const relPath = `./decisions/${d.frontmatter.id}.md`;
      const superId = d.frontmatter.supersedes ? `[[${d.frontmatter.supersedes}]]` : '-';
      md += `| [\`${d.frontmatter.id}\`](${relPath}) | ${dTitle} | \`${d.frontmatter.status}\` | ${d.frontmatter.updated} | ${superId} |\n`;
    }
    md += `\n`;
  }

  if (accepted.length > 0) {
    md += `## Accepted Decisions\n\n`;
    for (const d of accepted) {
      const dTitle = d.frontmatter.title || d.frontmatter.id;
      const relPath = `./decisions/${d.frontmatter.id}.md`;
      md += `### [\`${d.frontmatter.id}\`](${relPath}): ${dTitle}\n\n`;
      md += `- **Status:** \`${d.frontmatter.status}\` | **Created:** \`${d.frontmatter.created}\` | **Updated:** \`${d.frontmatter.updated}\` | **Wikilink:** \`[[${d.frontmatter.id}]]\`\n`;
      if (d.frontmatter.rationale) {
        md += `- **Rationale:** ${d.frontmatter.rationale}\n`;
      }
      md += `\n${d.body}\n\n---\n\n`;
    }
  }

  if (proposed.length > 0) {
    md += `## Proposed Decisions\n\n`;
    for (const d of proposed) {
      const dTitle = d.frontmatter.title || d.frontmatter.id;
      const relPath = `./decisions/${d.frontmatter.id}.md`;
      md += `### [PROPOSED] [\`${d.frontmatter.id}\`](${relPath}): ${dTitle}\n\n`;
      md += `${d.body}\n\n---\n\n`;
    }
  }

  return md;
}

/**
 * Compile INDEX.md view from all project records.
 */
export function generateIndexView(metadata: ProjectMetadata | null, records: MemoRecord[]): string {
  const title = metadata?.displayName || metadata?.projectId || 'Project';
  const now = new Date().toISOString();

  const byKind: Record<string, MemoRecord[]> = {};
  for (const r of records) {
    const kind = r.frontmatter.kind;
    if (!byKind[kind]) byKind[kind] = [];
    byKind[kind].push(r);
  }

  let md = `# Memory Vault Index — ${title}

<!-- AUTO-GENERATED BY spec-memo — DO NOT EDIT DIRECTLY -->
*Last compiled: ${now}*
*Git Remote: ${metadata?.gitRemote || 'local-only'}*
*Last seen root: \`${metadata?.lastSeenRoot || 'unknown'}\`*

## Inventory

| Kind | Active | Total |
|---|---|---|
`;

  const durableKinds = ['trap', 'decision', 'spec', 'plan', 'log', 'review'] as const;
  for (const kind of durableKinds) {
    const list = byKind[kind] || [];
    const active = list.filter((r) => r.frontmatter.status === 'active').length;
    md += `| \`${kind}\` | ${active} | ${list.length} |\n`;
  }

  md += `\n## Records by Kind\n\n`;

  for (const kind of durableKinds) {
    const list = byKind[kind] || [];
    if (list.length > 0) {
      md += `### ${kind.toUpperCase()} (${list.length})\n\n`;
      md += `| ID | Title / Slug | Status | Updated |\n`;
      md += `|---|---|---|---|\n`;
      for (const r of list) {
        const rTitle = r.frontmatter.title || r.frontmatter.relatedSlug || r.frontmatter.id;
        const kindSubdir = `${kind}s`;
        const relPath = `./${kindSubdir}/${r.frontmatter.id}.md`;
        md += `| [\`${r.frontmatter.id}\`](${relPath}) | ${rTitle} | \`${r.frontmatter.status}\` | ${r.frontmatter.updated} |\n`;
      }
      md += `\n`;
    }
  }

  return md;
}

/**
 * Rebuild TRAPS.md, DECISIONS.md, and INDEX.md in the project vault.
 */
export function rebuildCompiledViews(
  projectId: string,
  vaultRoot: string = getVaultRoot()
): { trapsCount: number; decisionsCount: number; totalRecords: number } {
  const projectDir = path.join(vaultRoot, 'projects', projectId);
  if (!fs.existsSync(projectDir)) {
    throw new Error(`Project vault not found: ${projectDir}`);
  }

  const metadata = getProjectMetadata(projectId, vaultRoot);
  const allRecords = scanProjectRecords(projectDir);

  const traps = allRecords.filter((r) => r.frontmatter.kind === 'trap');
  const decisions = allRecords.filter((r) => r.frontmatter.kind === 'decision');

  const trapsMd = generateTrapsView(metadata, traps);
  const decisionsMd = generateDecisionsView(metadata, decisions);
  const indexMd = generateIndexView(metadata, allRecords);

  fs.writeFileSync(path.join(projectDir, 'TRAPS.md'), trapsMd, 'utf8');
  fs.writeFileSync(path.join(projectDir, 'DECISIONS.md'), decisionsMd, 'utf8');
  fs.writeFileSync(path.join(projectDir, 'INDEX.md'), indexMd, 'utf8');

  return {
    trapsCount: traps.length,
    decisionsCount: decisions.length,
    totalRecords: allRecords.length
  };
}
