import * as fs from 'node:fs';
import * as path from 'node:path';
import { PromoteOptions, PromoteResult, MemoRecord } from './types.js';
import { getRecord, listProjectRecords } from './store.js';
import { resolveProjectIdentity } from './identity.js';
import { getVaultRoot } from './vault.js';
import { serializeRecord } from './schema.js';
import { isPathInside } from './safety.js';
import { formatAsSkill, rankActiveTraps } from './recurrence.js';

/**
 * Format a decision record into standard Nygard / ADR format.
 */
export function formatAsAdr(record: MemoRecord): string {
  const fm = record.frontmatter;
  const title = (fm.title as string) || fm.id || 'Architectural Decision';
  const status = (fm.status as string) || 'accepted';
  const date = (fm.updated || fm.created || new Date().toISOString()).slice(0, 10);
  const source = fm.source || 'agent';
  const tags = Array.isArray(fm.tags) ? fm.tags.join(', ') : 'architecture';

  const bodyTrimmed = record.body.trim();

  return `# ADR: ${title}

- **Status:** ${status.toUpperCase()}
- **Date:** ${date}
- **Author/Deciders:** ${source}
- **Tags:** ${tags}

## Context and Problem Statement

${bodyTrimmed}

## Decision Outcome

Chosen option: **${title}**, accepted as project standard.

## Consequences

### Positive Consequences
- Clear architectural boundary and shared team context.
- Documented rationale prevents future architectural regressions.

### Negative Consequences
- Changes to architectural direction require formal superseding records.

<!-- Generated by spec-memo promote (ADR format) -->
`;
}

/**
 * Format a decision record into MADR (Markdown Architectural Decision Records) format.
 */
export function formatAsMadr(record: MemoRecord): string {
  const fm = record.frontmatter;
  const title = (fm.title as string) || fm.id || 'Architectural Decision';
  const status = (fm.status as string) || 'accepted';
  const date = (fm.updated || fm.created || new Date().toISOString()).slice(0, 10);
  const source = fm.source || 'agent';

  const bodyTrimmed = record.body.trim();

  return `# ${title}

* Status: ${status}
* Deciders: ${source}
* Date: ${date}

Technical Story: \`${fm.id}\`

## Context and Problem Statement

${bodyTrimmed}

## Decision Drivers

* Clean isolation between product tree and working memory
* Consistent developer decision log

## Considered Options

* Option 1: **${title}** (Chosen)

## Decision Outcome

Chosen option: "**${title}**", because it satisfies architecture and safety constraints.

### Positive Consequences

* Explicit architecture record available to team members on clone
* Fast onboarding and audit trail

### Negative Consequences

* Must be updated or superseded when architecture evolves

<!-- Generated by spec-memo promote (MADR format) -->
`;
}

/**
 * Promote a vault record (e.g. decision, spec) into the consumer product repository.
 * Enforces a strict default-deny boundary: the target path MUST reside inside the product root.
 */
export async function promoteRecord(options: PromoteOptions): Promise<PromoteResult> {
  const vaultRoot = options.vaultRoot || getVaultRoot();
  const identity = resolveProjectIdentity(options.cwd || process.cwd(), { vaultRoot });
  const projectId = options.projectId || identity.projectId;

  const resolvedVault = path.resolve(vaultRoot);
  if (path.resolve(identity.rootPath) === resolvedVault || isPathInside(path.resolve(identity.rootPath), resolvedVault)) {
    throw new Error('promote requires a consumer product cwd/projectId; vault paths are not valid product roots.');
  }

  if (!options.destination || typeof options.destination !== 'string' || options.destination.trim().length === 0) {
    throw new Error('Destination path is required to promote a record into the product repository.');
  }

  const skillExport = options.format === 'skill';
  const lookupSingle = Boolean(options.id || options.slug);
  let record: MemoRecord | null = null;
  let skillRecords: MemoRecord[] = [];

  if (skillExport && !lookupSingle) {
    skillRecords = rankActiveTraps(listProjectRecords(vaultRoot, projectId), {
      layer: options.layer,
      limit: options.limit
    });
    if (skillRecords.length === 0) {
      throw new Error(
        'No active traps to compile for skill export. Record traps in the vault or pass an explicit id.'
      );
    }
  } else {
    record = await getRecord({
      cwd: options.cwd,
      projectId,
      vaultRoot,
      id: options.id,
      kind: options.kind,
      slug: options.slug
    });

    if (!record) {
      const lookup = options.id || `${options.kind || ''}/${options.slug || ''}`;
      throw new Error(`Record not found for promotion: ${lookup}`);
    }
    if (skillExport) {
      skillRecords = [record];
    }
  }

  // Resolve target path
  let destClean = options.destination.trim();
  let resolvedTarget = path.isAbsolute(destClean)
    ? path.resolve(destClean)
    : path.resolve(identity.rootPath, destClean);

  // If destination is a directory or ends with path separator, resolve filename
  if (
    destClean.endsWith('/') ||
    destClean.endsWith('\\') ||
    (fs.existsSync(resolvedTarget) && fs.statSync(resolvedTarget).isDirectory())
  ) {
    const slugSource = record || skillRecords[0];
    const slug = slugSource
      ? String(slugSource.frontmatter.slug || slugSource.frontmatter.id || 'decision')
      : 'SKILL';
    const isAdr =
      options.format === 'adr' ||
      options.format === 'madr' ||
      record?.frontmatter.kind === 'decision';
    const prefix = isAdr ? '0001-' : '';
    const filename = skillExport ? 'SKILL.md' : `${prefix}${slug}.md`;
    resolvedTarget = path.join(resolvedTarget, filename);
  }

  // Strict default-deny: destination MUST be inside consumer product root and not in .git
  if (!isPathInside(resolvedTarget, identity.rootPath)) {
    throw new Error(
      `Safety violation (Default Deny): Promote destination must be inside consumer product repository (${identity.rootPath}). Target: ${resolvedTarget}`
    );
  }

  const relCheck = path.relative(identity.rootPath, resolvedTarget).replace(/\\/g, '/');
  if (relCheck === '.git' || relCheck.startsWith('.git/')) {
    throw new Error(
      `Safety violation (Default Deny): Promote destination must not target .git directory. Target: ${resolvedTarget}`
    );
  }

  // Check if file already exists
  if (fs.existsSync(resolvedTarget) && !options.force) {
    throw new Error(
      `Target destination already exists: ${destClean}. Specify force: true to overwrite existing files.`
    );
  }

  // Ensure parent directory exists
  const parentDir = path.dirname(resolvedTarget);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  // Format content based on format option or record kind
  let fileContent: string;
  const requestedFormat = options.format || (record?.frontmatter.kind === 'decision' ? 'adr' : 'raw');

  if (requestedFormat === 'skill') {
    fileContent = formatAsSkill(skillRecords);
  } else if (requestedFormat === 'adr' && record && record.frontmatter.kind === 'decision') {
    fileContent = formatAsAdr(record);
  } else if (requestedFormat === 'madr' && record && record.frontmatter.kind === 'decision') {
    fileContent = formatAsMadr(record);
  } else if (record) {
    fileContent = serializeRecord({
      frontmatter: record.frontmatter,
      body: record.body
    });
  } else {
    throw new Error('Record not found for promotion.');
  }

  fs.writeFileSync(resolvedTarget, fileContent, 'utf8');
  const bytesWritten = Buffer.byteLength(fileContent, 'utf8');

  const relativeDest = path.relative(identity.rootPath, resolvedTarget).replace(/\\/g, '/');
  const primary = record || skillRecords[0];

  return {
    id: primary ? primary.frontmatter.id : 'skill-export',
    kind: primary ? primary.frontmatter.kind : 'trap',
    destination: relativeDest,
    targetPath: resolvedTarget,
    bytesWritten,
    format: requestedFormat
  };
}
