import * as fs from 'node:fs';
import * as path from 'node:path';
import { DerivedRuleCandidate, DeriveRulesResult, MemoRecord } from './types.js';
import { upsertRecord } from './store.js';
import { slugify } from './store.js';

interface SignalDefinition {
  regex: RegExp;
  category: string;
  confidence: number;
  prefix: string;
}

const RULE_SIGNALS: SignalDefinition[] = [
  {
    regex: /(?:^|\.\s+|\n)(?:always|make sure to always|ensure you always|every time)\s+([^.\n]{10,200})/i,
    category: 'process',
    confidence: 0.85,
    prefix: 'Always'
  },
  {
    regex: /(?:^|\.\s+|\n)(?:never|do not|don't|under no circumstances)\s+([^.\n]{10,200})/i,
    category: 'constraint',
    confidence: 0.9,
    prefix: 'Never'
  },
  {
    regex: /(?:^|\.\s+|\n)(?:must not|cannot|should never)\s+([^.\n]{10,200})/i,
    category: 'constraint',
    confidence: 0.9,
    prefix: 'Must Not'
  },
  {
    regex: /(?:^|\.\s+|\n)(?:must|strictly required to|mandatory that)\s+([^.\n]{10,200})/i,
    category: 'architecture',
    confidence: 0.85,
    prefix: 'Must'
  },
  {
    regex: /(?:^|\.\s+|\n)(?:refuse|reject|prohibit)\s+([^.\n]{10,200})/i,
    category: 'security',
    confidence: 0.9,
    prefix: 'Prohibit'
  }
];

function cleanRuleText(text: string): string {
  return text
    .trim()
    .replace(/^[:,\-\s]+/, '')
    .replace(/[;,\s]+$/, '')
    .replace(/\s+/g, ' ');
}

function deriveTitleFromPattern(prefix: string, text: string): string {
  const words = text.split(' ').slice(0, 8).join(' ');
  return `${prefix}: ${words}${words.length < text.length ? '...' : ''}`;
}

export function extractRulesFromPrompts(prompts: MemoRecord[]): DerivedRuleCandidate[] {
  const candidateMap = new Map<string, {
    ruleTitle: string;
    pattern: string;
    category: string;
    confidence: number;
    promptIds: Set<string>;
    occurrences: number;
  }>();

  for (const prompt of prompts) {
    const text = prompt.body || '';
    const promptId = prompt.frontmatter.id;

    for (const signal of RULE_SIGNALS) {
      let match: RegExpExecArray | null;
      const globalRegex = new RegExp(signal.regex.source, 'gi');

      while ((match = globalRegex.exec(text)) !== null) {
        const rawContent = match[1];
        if (!rawContent) continue;
        const cleaned = cleanRuleText(rawContent);
        if (cleaned.length < 15) continue;

        // Normalize key to group similar instructions
        const normKey = cleaned.toLowerCase().replace(/[^a-z0-9]/g, ' ').replace(/\s+/g, ' ').trim();
        const existing = candidateMap.get(normKey);

        if (existing) {
          existing.occurrences += 1;
          existing.confidence = Math.min(0.99, existing.confidence + 0.05);
          existing.promptIds.add(promptId);
        } else {
          const title = deriveTitleFromPattern(signal.prefix, cleaned);
          candidateMap.set(normKey, {
            ruleTitle: title,
            pattern: `${signal.prefix} ${cleaned}`,
            category: signal.category,
            confidence: signal.confidence,
            promptIds: new Set([promptId]),
            occurrences: 1
          });
        }
      }
    }
  }

  const results: DerivedRuleCandidate[] = [];
  for (const [, item] of candidateMap.entries()) {
    const sourcePromptIds = Array.from(item.promptIds);
    const suggestedBody = `### Derived Rule: ${item.ruleTitle}
- **Category:** \`${item.category}\`
- **Confidence:** ${Math.round(item.confidence * 100)}% (${item.occurrences} signal${item.occurrences > 1 ? 's' : ''})
- **Pattern:** ${item.pattern}
- **Source Prompts:** ${sourcePromptIds.map((id) => `\`${id}\``).join(', ')}

#### Instruction
${item.pattern}.
`;

    results.push({
      ruleTitle: item.ruleTitle,
      pattern: item.pattern,
      category: item.category,
      confidence: Math.round(item.confidence * 100) / 100,
      sourcePromptIds,
      suggestedBody
    });
  }

  return results.sort((a, b) => b.confidence - a.confidence || b.sourcePromptIds.length - a.sourcePromptIds.length);
}

export function formatDerivedRulesForExport(
  rules: DerivedRuleCandidate[],
  format: 'cursor' | 'copilot' | 'claude' | 'gemini' | 'markdown' = 'markdown'
): string {
  const now = new Date().toISOString();
  if (format === 'cursor') {
    let out = `---
description: Derived AI Rules from spec-memo prompt history
globs: *
---
# Derived Project Rules

<!-- AUTO-GENERATED BY spec-memo derive-rules (${now}) -->

`;
    for (const r of rules) {
      out += `## ${r.ruleTitle}\n\n${r.pattern}.\n\n`;
    }
    return out;
  }

  if (format === 'copilot') {
    let out = `# GitHub Copilot Instructions

<!-- AUTO-GENERATED BY spec-memo derive-rules (${now}) -->

`;
    for (const r of rules) {
      out += `- **${r.ruleTitle}**: ${r.pattern}.\n`;
    }
    return out;
  }

  if (format === 'claude' || format === 'gemini') {
    let out = `# Project Instructions (${format.toUpperCase()})

<!-- AUTO-GENERATED BY spec-memo derive-rules (${now}) -->

`;
    for (const r of rules) {
      out += `### ${r.ruleTitle}\n${r.pattern}.\n\n`;
    }
    return out;
  }

  // Generic Markdown
  let out = `# Derived Project Rules & Constraints

<!-- AUTO-GENERATED BY spec-memo derive-rules (${now}) -->
*Total Rules: ${rules.length}*

`;
  for (const r of rules) {
    out += `## ${r.ruleTitle}\n`;
    out += `- **Category:** \`${r.category}\` | **Confidence:** ${Math.round(r.confidence * 100)}%\n`;
    out += `- **Pattern:** ${r.pattern}\n\n`;
  }
  return out;
}
