import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { MemoRecord, VaultConfig } from './types.js';
import { getSubdirForKind, listProjectRecords, slugify } from './store.js';
import { commitVaultChange, getProjectMetadata, readVaultConfig, withVaultLockSync } from './vault.js';
import { isPathInside, sanitizeToolOutput } from './safety.js';
import { scheduleHybridPush } from './hybrid-sync.js';
import { inspectAgentIo } from './io-guard.js';
import {
  emitAiWikiActivity,
  recordAiOpsEvent,
  resolveAiConfig,
  resolveVaultAiAgent,
  type VaultAiAgent,
  type VaultAiWikiSnapshot
} from './ai/index.js';

export const WIKI_AUTO_MARKER = '<!-- AUTO-GENERATED BY spec-memo wiki — DO NOT EDIT DIRECTLY -->';
export const WIKI_PROJECT_REQUIRED = 'A specific projectId is required';
const LIST_CAP = 25;
const DEFAULT_AI_TIMEOUT_MS = 15000;
const SNAPSHOT_MAX_BYTES = 32 * 1024;
const EMPTY_TRAPS = '*No active traps recorded for this project yet.*';
const EMPTY_DECISIONS = '*No architecture decisions recorded for this project yet.*';
const EMPTY_SPECS = '*No specs or plans recorded for this project yet.*';
const EMPTY_SESSIONS = '*No sessions recorded for this project yet.*';

/** Stable topic titles whose slugified ids must survive AI polish. */
export const WIKI_REQUIRED_H2_TITLES = [
  'Overview',
  'Topic catalog',
  'Architecture & decisions',
  'Active traps',
  'Specs & plans',
  'Sessions',
  'Structured links'
] as const;

const TOPIC_CATALOG_ENTRIES: Array<{ title: string; description: string }> = [
  {
    title: 'Architecture & decisions',
    description: 'Architecture decisions and ADRs for this project.'
  },
  {
    title: 'Active traps',
    description: 'Active anti-regression traps and failure modes.'
  },
  {
    title: 'Specs & plans',
    description: 'Feature specs and delivery plans.'
  },
  {
    title: 'Sessions',
    description: 'Recent agent session summaries.'
  },
  {
    title: 'Structured links',
    description: 'Compiled views and vault record links.'
  }
];

export type WikiErrorCode = 'INVALID_PROJECT' | 'NOT_FOUND';

export class WikiError extends Error {
  readonly code: WikiErrorCode;
  readonly httpStatus: number;

  constructor(code: WikiErrorCode, message: string, httpStatus: number) {
    super(message);
    this.name = 'WikiError';
    this.code = code;
    this.httpStatus = httpStatus;
  }
}

export interface WikiSources {
  projectId: string;
  projectTitle: string;
  gitRemote: string | null;
  trapsActive: MemoRecord[];
  decisions: MemoRecord[];
  specsPlans: MemoRecord[];
  sessions: MemoRecord[];
  inventory: {
    traps: number;
    trapsActive: number;
    decisions: number;
    specs: number;
    plans: number;
    sessions: number;
    prompts: number;
  };
}

export type WikiSnapshot = VaultAiWikiSnapshot;

export interface WikiFilePayload {
  projectId: string;
  markdown: string;
  lastGenerated: string | null;
  exists: boolean;
}

export interface WikiSectionPayload {
  id: string;
  title: string;
  markdown: string;
}

export interface WikiRegenerateResult {
  ok: true;
  projectId: string;
  lastGenerated: string;
  aiPolished: boolean;
  aiError?: string;
}

export type PolishWikiMarkdown = (input: {
  markdown: string;
  snapshot: WikiSnapshot;
}) => Promise<string> | string;

export interface RegenerateWikiOptions {
  projectId: string;
  vaultRoot: string;
  polishWikiMarkdown?: PolishWikiMarkdown;
  /** Optional agent override (tests); production uses resolveVaultAiAgent. */
  aiAgent?: VaultAiAgent;
  now?: Date;
}

function invalidProject(): never {
  throw new WikiError('INVALID_PROJECT', WIKI_PROJECT_REQUIRED, 400);
}

function notFound(): never {
  throw new WikiError('NOT_FOUND', 'Not found', 404);
}

export function assertSafeProjectId(projectId: string | null | undefined, vaultRoot: string): string {
  if (projectId == null || typeof projectId !== 'string') invalidProject();
  const id = projectId.trim();
  if (!id || id.toLowerCase() === 'all') invalidProject();
  if (id.includes('/') || id.includes('\\') || id.includes('..') || id.includes('\0')) {
    invalidProject();
  }
  const projectsDir = path.resolve(vaultRoot, 'projects');
  const resolved = path.resolve(projectsDir, id);
  if (!isPathInside(resolved, projectsDir) || resolved === projectsDir) {
    invalidProject();
  }
  return id;
}

export function wikiProjectExists(projectId: string, vaultRoot: string): boolean {
  const id = assertSafeProjectId(projectId, vaultRoot);
  const dir = path.resolve(vaultRoot, 'projects', id);
  try {
    return fs.existsSync(dir) && fs.statSync(dir).isDirectory();
  } catch {
    return false;
  }
}

export function wikiFilePath(projectId: string, vaultRoot: string): string {
  const id = assertSafeProjectId(projectId, vaultRoot);
  return path.join(vaultRoot, 'projects', id, 'WIKI.md');
}

function requireExistingProject(projectId: string | null | undefined, vaultRoot: string): string {
  const id = assertSafeProjectId(projectId, vaultRoot);
  if (!wikiProjectExists(id, vaultRoot)) notFound();
  return id;
}

function sortNewest(a: MemoRecord, b: MemoRecord): number {
  return (b.frontmatter.updated || b.frontmatter.created || '').localeCompare(
    a.frontmatter.updated || a.frontmatter.created || ''
  );
}

function mdLink(kind: MemoRecord['frontmatter']['kind'], id: string): string {
  const sub = getSubdirForKind(kind);
  return `[${id}](./${sub}/${id}.md)`;
}

function bulletLinks(records: MemoRecord[], empty: string): string {
  if (records.length === 0) return empty;
  const shown = records.slice(0, LIST_CAP);
  const lines = shown.map((r) => {
    const title = r.frontmatter.title || r.frontmatter.id;
    const id = r.frontmatter.id;
    return `- ${mdLink(r.frontmatter.kind, id)} (\`[[${id}]]\`): ${title}`;
  });
  if (records.length > LIST_CAP) {
    lines.push(`- *${records.length - LIST_CAP} more in compiled views / inventory.*`);
  }
  return lines.join('\n');
}

export function collectWikiSources(projectId: string, vaultRoot: string): WikiSources {
  const id = requireExistingProject(projectId, vaultRoot);
  const records = listProjectRecords(vaultRoot, id);
  const meta = getProjectMetadata(id, vaultRoot);
  const traps = records.filter((r) => r.frontmatter.kind === 'trap');
  const trapsActive = traps.filter((r) => r.frontmatter.status === 'active').sort(sortNewest);
  const decisions = records
    .filter((r) => r.frontmatter.kind === 'decision' && r.frontmatter.status !== 'archived' && r.frontmatter.status !== 'superseded')
    .sort(sortNewest);
  const specsPlans = records
    .filter(
      (r) =>
        (r.frontmatter.kind === 'spec' || r.frontmatter.kind === 'plan') &&
        r.frontmatter.status !== 'archived' &&
        r.frontmatter.status !== 'superseded'
    )
    .sort(sortNewest);
  const sessions = records.filter((r) => r.frontmatter.kind === 'session').sort(sortNewest);
  const prompts = records.filter((r) => r.frontmatter.kind === 'prompt');
  return {
    projectId: id,
    projectTitle: meta?.displayName || id,
    gitRemote: meta?.gitRemote || null,
    trapsActive,
    decisions,
    specsPlans,
    sessions,
    inventory: {
      traps: traps.length,
      trapsActive: trapsActive.length,
      decisions: records.filter((r) => r.frontmatter.kind === 'decision').length,
      specs: records.filter((r) => r.frontmatter.kind === 'spec').length,
      plans: records.filter((r) => r.frontmatter.kind === 'plan').length,
      sessions: sessions.length,
      prompts: prompts.length
    }
  };
}

export function loadWikiTemplate(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.join(here, 'wiki', 'template.md'),
    path.join(here, '..', 'src', 'wiki', 'template.md')
  ];
  for (const file of candidates) {
    if (fs.existsSync(file)) {
      return fs.readFileSync(file, 'utf8');
    }
  }
  throw new Error('Wiki template.md is missing from the package');
}

function fillPlaceholder(template: string, name: string, value: string): string {
  return template.split(`{{${name}}}`).join(value);
}

export function renderWikiMarkdown(sources: WikiSources, template: string, lastGenerated: string): string {
  const inv = sources.inventory;
  const overviewParts = [
    `${sources.projectTitle} (\`${sources.projectId}\`) is a spec-memo vault project.`
  ];
  if (sources.gitRemote) {
    overviewParts.push(`Git remote: \`${sources.gitRemote}\`.`);
  }
  overviewParts.push(
    `Inventory: ${inv.traps} traps (${inv.trapsActive} active), ${inv.decisions} decisions, ${inv.specs} specs, ${inv.plans} plans, ${inv.sessions} sessions, ${inv.prompts} prompts.`
  );

  const structured: string[] = [
    `- [INDEX.md](./INDEX.md)`,
    `- [TRAPS.md](./TRAPS.md)`,
    `- [DECISIONS.md](./DECISIONS.md)`
  ];
  for (const r of sources.trapsActive.slice(0, LIST_CAP)) {
    structured.push(`- ${mdLink('trap', r.frontmatter.id)}`);
  }
  for (const r of sources.decisions.slice(0, LIST_CAP)) {
    structured.push(`- ${mdLink('decision', r.frontmatter.id)}`);
  }
  for (const r of sources.specsPlans.slice(0, LIST_CAP)) {
    structured.push(`- ${mdLink(r.frontmatter.kind, r.frontmatter.id)}`);
  }

  const inventory = `*Inventory: traps ${inv.traps} (active ${inv.trapsActive}), decisions ${inv.decisions}, specs ${inv.specs}, plans ${inv.plans}, sessions ${inv.sessions}, prompts ${inv.prompts}.*`;

  const topicCatalog = TOPIC_CATALOG_ENTRIES.map((entry) => {
    const id = slugify(entry.title);
    return `- [${entry.title}](#${id}): ${entry.description}`;
  }).join('\n');

  let out = template;
  const values: Record<string, string> = {
    projectTitle: sources.projectTitle,
    projectId: sources.projectId,
    overview: overviewParts.join(' '),
    topicCatalog,
    architectureDecisions: bulletLinks(sources.decisions, EMPTY_DECISIONS),
    decisionLinks: sources.decisions.length
      ? sources.decisions.slice(0, LIST_CAP).map((d) => `- ${mdLink('decision', d.frontmatter.id)} \`[[${d.frontmatter.id}]]\``).join('\n')
      : '',
    activeTraps: bulletLinks(sources.trapsActive, EMPTY_TRAPS),
    specsPlans: bulletLinks(sources.specsPlans, EMPTY_SPECS),
    sessions: bulletLinks(sources.sessions, EMPTY_SESSIONS),
    structuredLinks: structured.join('\n'),
    inventory,
    lastGenerated
  };
  for (const [key, value] of Object.entries(values)) {
    out = fillPlaceholder(out, key, value);
  }
  if (out.includes('{{')) {
    out = out.replace(/\{\{[^}]+\}\}/g, '');
  }
  return out;
}

export function parseLastGenerated(markdown: string): string | null {
  const m = markdown.match(/\*Last generated:\s*([0-9]{4}-[0-9]{2}-[0-9]{2}T[^\s*]+)\*/);
  return m ? m[1].trim() : null;
}

export function persistWikiMarkdown(projectId: string, vaultRoot: string, markdown: string): string {
  const id = requireExistingProject(projectId, vaultRoot);
  const filePath = wikiFilePath(id, vaultRoot);
  const dir = path.dirname(filePath);
  if (!isPathInside(path.resolve(filePath), path.resolve(vaultRoot, 'projects', id))) {
    invalidProject();
  }
  withVaultLockSync(vaultRoot, () => {
    if (!fs.existsSync(dir)) {
      notFound();
    }
    fs.writeFileSync(filePath, markdown, 'utf8');
  });
  try {
    commitVaultChange(`wiki ${id}`, vaultRoot, [path.join('projects', id)]);
  } catch {
    // fail-open
  }
  try {
    scheduleHybridPush(vaultRoot, id);
  } catch {
    // fail-open
  }
  return filePath;
}

export function readWikiFile(projectId: string | null | undefined, vaultRoot: string): WikiFilePayload {
  const id = requireExistingProject(projectId, vaultRoot);
  const filePath = wikiFilePath(id, vaultRoot);
  if (!fs.existsSync(filePath)) {
    return { projectId: id, markdown: '', lastGenerated: null, exists: false };
  }
  const markdown = fs.readFileSync(filePath, 'utf8');
  return {
    projectId: id,
    markdown,
    lastGenerated: parseLastGenerated(markdown),
    exists: true
  };
}

export function splitWikiSections(markdown: string): Array<{ id: string; title: string; markdown: string }> {
  const lines = markdown.split(/\r?\n/);
  const sections: Array<{ id: string; title: string; markdown: string }> = [];
  let current: { title: string; lines: string[] } | null = null;
  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+)$/);
    if (h2) {
      if (current) {
        sections.push({
          id: slugify(current.title),
          title: current.title,
          markdown: current.lines.join('\n').trim()
        });
      }
      current = { title: h2[1].trim(), lines: [line] };
    } else if (current) {
      current.lines.push(line);
    }
  }
  if (current) {
    sections.push({
      id: slugify(current.title),
      title: current.title,
      markdown: current.lines.join('\n').trim()
    });
  }
  return sections;
}

export function readWikiSection(
  projectId: string | null | undefined,
  sectionId: string | null | undefined,
  vaultRoot: string
): WikiSectionPayload {
  const payload = readWikiFile(projectId, vaultRoot);
  if (!payload.exists) notFound();
  const id = (sectionId || '').trim();
  if (!id) notFound();
  const section = splitWikiSections(payload.markdown).find((s) => s.id === id);
  if (!section) notFound();
  return section;
}

function isLegacyWikiAiEnabled(config: VaultConfig): boolean {
  if (config.wiki?.aiEnabled === true) return true;
  if (config.wiki?.aiEnabled === false) return false;
  return process.env.SPEC_MEMO_WIKI_AI === '1';
}

function wikiTimeoutMs(config: VaultConfig): number {
  const n = config.wiki?.timeoutMs;
  return typeof n === 'number' && n > 0 ? n : DEFAULT_AI_TIMEOUT_MS;
}

function assistantTimeoutMs(config: VaultConfig): number {
  const ai = resolveAiConfig(config);
  return typeof ai.timeoutMs === 'number' && ai.timeoutMs > 0 ? ai.timeoutMs : DEFAULT_AI_TIMEOUT_MS;
}

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('wiki AI polish timed out')), ms);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (err) => {
        clearTimeout(timer);
        reject(err);
      }
    );
  });
}

function shortAiError(err: unknown): string {
  const raw = err instanceof Error ? err.message : String(err);
  const clipped = raw.replace(/\s+/g, ' ').trim().slice(0, 180);
  return String(sanitizeToolOutput(clipped || 'polish failed'));
}

function recordRef(r: MemoRecord): { id: string; kind: string; title: string } {
  return {
    id: String(r.frontmatter.id),
    kind: String(r.frontmatter.kind),
    title: String(r.frontmatter.title || r.frontmatter.id)
  };
}

/**
 * Build a bounded snapshot from collectWikiSources output (same regenerate call).
 * Always keeps inventory counts; truncates oldest/lowest-priority records first
 * to stay under ~32 KiB UTF-8.
 */
export function buildWikiSnapshot(sources: WikiSources, maxBytes = SNAPSHOT_MAX_BYTES): WikiSnapshot {
  const buckets: Array<{ id: string; kind: string; title: string }>[] = [
    sources.trapsActive.map(recordRef),
    sources.decisions.map(recordRef),
    sources.specsPlans.map(recordRef),
    sources.sessions.map(recordRef)
  ];
  let records = buckets.flat();
  const base: WikiSnapshot = {
    projectId: sources.projectId,
    inventory: { ...sources.inventory },
    records
  };
  const sizeOf = (snap: WikiSnapshot) => Buffer.byteLength(JSON.stringify(snap), 'utf8');
  if (sizeOf(base) <= maxBytes) return base;

  // Drop from the end of later buckets first (sessions → specs/plans → decisions → traps).
  for (let b = buckets.length - 1; b >= 0; b--) {
    while (buckets[b].length > 0 && sizeOf({ ...base, records: buckets.flat() }) > maxBytes) {
      buckets[b].pop();
    }
  }
  records = buckets.flat();
  return { projectId: sources.projectId, inventory: { ...sources.inventory }, records };
}

export function requiredWikiH2Slugs(): string[] {
  return WIKI_REQUIRED_H2_TITLES.map((title) => slugify(title));
}

export function wikiHasRequiredH2Slugs(markdown: string): boolean {
  const present = new Set(splitWikiSections(markdown).map((s) => s.id));
  return requiredWikiH2Slugs().every((id) => present.has(id));
}

/**
 * Bind polish from a VaultAiAgent (production choke point with resolveVaultAiAgent).
 * Used by status/CLI regenerate wiring and regenerateWiki fallback.
 */
export function bindWikiPolishFromAgent(agent: VaultAiAgent | null | undefined): PolishWikiMarkdown | undefined {
  if (!agent || typeof agent.polishWikiMarkdown !== 'function') return undefined;
  if (!agent.isAvailable()) return undefined;
  const polish = agent.polishWikiMarkdown.bind(agent);
  return (input) => polish(input);
}

/**
 * Production helper: resolve agent via the same choke point as refine (AC14).
 */
export function resolveWikiPolishFromVault(vaultRoot: string): PolishWikiMarkdown | undefined {
  try {
    const { agent, config } = resolveVaultAiAgent(vaultRoot);
    if (config.enabled !== true) return undefined;
    return bindWikiPolishFromAgent(agent);
  } catch {
    return undefined;
  }
}

function emitWikiOps(
  vaultRoot: string,
  ok: boolean,
  durationMs: number,
  projectId: string,
  error?: string
): void {
  try {
    emitAiWikiActivity(ok, durationMs, projectId);
  } catch {
    // fail-open
  }
  try {
    const { config } = readVaultConfig(vaultRoot);
    const ai = resolveAiConfig(config);
    recordAiOpsEvent({
      vaultRoot,
      config: ai,
      operation: 'wiki',
      ok,
      durationMs,
      projectId,
      ...(error ? { error } : {}),
      metadata: { surface: 'wiki-regenerate' }
    });
  } catch {
    // fail-open
  }
}

export async function regenerateWiki(options: RegenerateWikiOptions): Promise<WikiRegenerateResult> {
  const id = requireExistingProject(options.projectId, options.vaultRoot);
  const lastGenerated = (options.now || new Date()).toISOString();
  const sources = collectWikiSources(id, options.vaultRoot);
  const snapshot = buildWikiSnapshot(sources);
  const template = loadWikiTemplate();
  const deterministic = renderWikiMarkdown(sources, template, lastGenerated);
  let markdown = deterministic;
  let aiPolished = false;
  let aiError: string | undefined;

  const { config } = readVaultConfig(options.vaultRoot);
  const aiConfig = resolveAiConfig(config);
  const legacyEnabled = isLegacyWikiAiEnabled(config);

  let polish: PolishWikiMarkdown | undefined = options.polishWikiMarkdown;
  let useAssistantTimeout = false;

  if (aiConfig.enabled === true) {
    useAssistantTimeout = true;
    let agent = options.aiAgent;
    if (!agent) {
      try {
        agent = resolveVaultAiAgent(options.vaultRoot, aiConfig).agent;
      } catch {
        agent = undefined;
      }
    }
    if (!agent || !agent.isAvailable()) {
      if (!polish) {
        aiError = 'unavailable';
      }
    } else if (!polish) {
      polish = bindWikiPolishFromAgent(agent);
      if (!polish) {
        aiError = 'no provider';
      }
    }
  } else if (legacyEnabled) {
    // Legacy wiki.aiEnabled / SPEC_MEMO_WIKI_AI: injected callback only (tests).
    if (!polish) {
      aiError = 'no provider';
    }
  } else {
    polish = undefined;
  }

  const shouldPolish =
    typeof polish === 'function' &&
    (aiConfig.enabled === true || legacyEnabled);

  if (shouldPolish && polish) {
    const started = Date.now();
    const timeoutMs = useAssistantTimeout ? assistantTimeoutMs(config) : wikiTimeoutMs(config);
    try {
      const snapshotText = JSON.stringify(snapshot);
      const promptScan = inspectAgentIo(`${snapshotText}\n${deterministic}`);
      if (!promptScan.ok) {
        throw new Error('IO_GUARD refused wiki polish input');
      }
      const polished = await withTimeout(
        Promise.resolve(polish({ markdown: deterministic, snapshot })),
        timeoutMs
      );
      if (typeof polished !== 'string' || polished.trim().length === 0) {
        throw new Error('empty polish output');
      }
      const outScan = inspectAgentIo(polished);
      if (!outScan.ok) {
        throw new Error('IO_GUARD refused wiki polish output');
      }
      const safe = String(sanitizeToolOutput(polished));
      if (!wikiHasRequiredH2Slugs(safe)) {
        throw new Error('polished wiki missing required h2 sections');
      }
      markdown = safe;
      aiPolished = true;
      emitWikiOps(options.vaultRoot, true, Date.now() - started, id);
    } catch (err) {
      markdown = deterministic;
      aiPolished = false;
      aiError = shortAiError(err);
      emitWikiOps(options.vaultRoot, false, Date.now() - started, id, aiError);
    }
  }

  persistWikiMarkdown(id, options.vaultRoot, markdown);
  return {
    ok: true,
    projectId: id,
    lastGenerated: parseLastGenerated(markdown) || lastGenerated,
    aiPolished,
    ...(aiError ? { aiError } : {})
  };
}
